project:
  name: "Deep Learning Model for Online Harassment Detection"
  random_seed: 42

labels:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate

dataset:
  train_ratio: 0.80
  validation_ratio: 0.10
  test_ratio: 0.10

model:
  name: "xlm-roberta-base"

tokenization:
  max_length: 256

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  models: "models"
  checkpoints: "checkpoints"
